# Generated by Django 3.2.9 on 2021-12-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_blog', '0007_alter_comment_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
